language: node_js

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules
    - dist

env:
  global:
    - GITHUB_ORG="https://GH_TOKEN@github.com"
    - REPO_NAME="angular-redux-todo"
    - GITHUB_NAME="railsstudent"
    - GITHUB_EMAIL="cleung334@gmail.com"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --pure-lockfile

script:
  - yarn audit
  - yarn lint
  - yarn build-ngh

after_success:
  - ngh --repo="$GITHUB_ORG/$GITHUB_NAME/$REPO_NAME.git" --name="$GITHUB_NAME" --email="$GITHUB_EMAIL" --no-silent

branches:
  only:
    - master
